# Generated by Django 5.2 on 2026-01-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_batch_battery'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='technical_outputs',
            field=models.ManyToManyField(blank=True, related_name='questions', to='inventory.technicaloutputchoice'),
        ),
    ]
