# Generated by Django 5.2 on 2026-01-02 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_testquestion_technical_outputs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(editable=False, help_text='Unique service case identifier (e.g., SVC-2025-0001)', max_length=20, unique=True)),
                ('service_date', models.DateField(help_text='Date when service was performed')),
                ('technician_name', models.CharField(help_text='Name of the service technician', max_length=100)),
                ('issue_description', models.TextField(help_text='Description of the issue reported')),
                ('actions_taken', models.TextField(help_text='Actions taken during service')),
                ('remarks', models.TextField(blank=True, help_text='Additional notes or remarks')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='open', help_text='Current status of the service case', max_length=20)),
                ('attachments', models.FileField(blank=True, help_text='Service photos, test reports, or other attachments', null=True, upload_to='service_attachments/%Y/%m/')),
                ('spare_parts_used', models.JSONField(blank=True, help_text='JSON field to store spare parts details', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barcode', models.ForeignKey(blank=True, help_text='Barcode being serviced', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_cases', to='inventory.barcode')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_cases', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(blank=True, help_text='Reference to the original test record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_cases', to='inventory.test')),
            ],
            options={
                'verbose_name': 'Service Case',
                'verbose_name_plural': 'Service Cases',
                'ordering': ['-created_at'],
            },
        ),
    ]
