# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_servicecase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(
                choices=[('admin', 'Admin'), ('batch', 'Batch Generation'), ('tester', 'Tester'), ('service', 'Service')],
                default='tester',
                max_length=20
            ),
        ),
    ]
