# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_update_role_choices'),
    ]

    operations = [
        # Barcode indexes
        migrations.AddIndex(
            model_name='barcode',
            index=models.Index(fields=['sequence_number'], name='inventory_barcode_sequence_number_idx'),
        ),
        migrations.AddIndex(
            model_name='barcode',
            index=models.Index(fields=['batch'], name='inventory_barcode_batch_idx'),
        ),
        migrations.AddIndex(
            model_name='barcode',
            index=models.Index(fields=['sku'], name='inventory_barcode_sku_idx'),
        ),

        # Test indexes
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['barcode'], name='inventory_test_barcode_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['overall_status'], name='inventory_test_overall_status_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['test_date'], name='inventory_test_test_date_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['sku', 'batch'], name='inventory_test_sku_batch_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['-test_date'], name='inventory_test_test_date_desc_idx'),
        ),

        # ServiceCase indexes
        migrations.AddIndex(
            model_name='servicecase',
            index=models.Index(fields=['case_id'], name='inventory_servicecase_case_id_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecase',
            index=models.Index(fields=['barcode'], name='inventory_servicecase_barcode_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecase',
            index=models.Index(fields=['status'], name='inventory_servicecase_status_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecase',
            index=models.Index(fields=['service_date'], name='inventory_servicecase_service_date_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecase',
            index=models.Index(fields=['technician_name'], name='inventory_servicecase_technician_name_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecase',
            index=models.Index(fields=['-created_at'], name='inventory_servicecase_created_at_desc_idx'),
        ),
    ]
