# Generated by Django 5.2 on 2026-01-02 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the technician', max_length=100, unique=True)),
                ('employee_id', models.CharField(blank=True, help_text='Employee ID (optional)', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this technician is active')),
                ('contact_number', models.CharField(blank=True, help_text='Contact number (optional)', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Technician',
                'verbose_name_plural': 'Technicians',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='servicecase',
            name='inventory_servicecase_technician_name_idx',
        ),
        migrations.RenameIndex(
            model_name='barcode',
            new_name='inventory_b_sequenc_7320df_idx',
            old_name='inventory_barcode_sequence_number_idx',
        ),
        migrations.RenameIndex(
            model_name='barcode',
            new_name='inventory_b_batch_i_0263fd_idx',
            old_name='inventory_barcode_batch_idx',
        ),
        migrations.RenameIndex(
            model_name='barcode',
            new_name='inventory_b_sku_id_fccc27_idx',
            old_name='inventory_barcode_sku_idx',
        ),
        migrations.RenameIndex(
            model_name='servicecase',
            new_name='inventory_s_case_id_eb731c_idx',
            old_name='inventory_servicecase_case_id_idx',
        ),
        migrations.RenameIndex(
            model_name='servicecase',
            new_name='inventory_s_barcode_4f5e6b_idx',
            old_name='inventory_servicecase_barcode_idx',
        ),
        migrations.RenameIndex(
            model_name='servicecase',
            new_name='inventory_s_status_242b20_idx',
            old_name='inventory_servicecase_status_idx',
        ),
        migrations.RenameIndex(
            model_name='servicecase',
            new_name='inventory_s_service_5bb7d8_idx',
            old_name='inventory_servicecase_service_date_idx',
        ),
        migrations.RenameIndex(
            model_name='servicecase',
            new_name='inventory_s_created_547679_idx',
            old_name='inventory_servicecase_created_at_desc_idx',
        ),
        migrations.RenameIndex(
            model_name='test',
            new_name='inventory_t_barcode_f5d5f6_idx',
            old_name='inventory_test_barcode_idx',
        ),
        migrations.RenameIndex(
            model_name='test',
            new_name='inventory_t_overall_169400_idx',
            old_name='inventory_test_overall_status_idx',
        ),
        migrations.RenameIndex(
            model_name='test',
            new_name='inventory_t_test_da_8d2f9c_idx',
            old_name='inventory_test_test_date_idx',
        ),
        migrations.RenameIndex(
            model_name='test',
            new_name='inventory_t_sku_id_15e445_idx',
            old_name='inventory_test_sku_batch_idx',
        ),
        migrations.RenameIndex(
            model_name='test',
            new_name='inventory_t_test_da_fc4ff5_idx',
            old_name='inventory_test_test_date_desc_idx',
        ),
        migrations.RemoveField(
            model_name='servicecase',
            name='technician_name',
        ),
        migrations.AddField(
            model_name='servicecase',
            name='technician',
            field=models.ForeignKey(blank=True, help_text='Service technician assigned to this case', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.technician'),
        ),
        migrations.AddIndex(
            model_name='servicecase',
            index=models.Index(fields=['technician'], name='inventory_s_technic_50605b_idx'),
        ),
    ]
