# Generated by Django 5.2 on 2026-01-02 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_technician_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('test_failed', 'Test Failed'), ('test_passed', 'Test Passed'), ('service_created', 'Service Case Created'), ('service_updated', 'Service Case Updated'), ('service_completed', 'Service Case Completed'), ('batch_created', 'Batch Created'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('system_error', 'System Error'), ('validation_error', 'Validation Error'), ('performance_issue', 'Performance Issue'), ('other', 'Other')], db_index=True, help_text='Type of event', max_length=50)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='info', help_text='Log level', max_length=20)),
                ('title', models.CharField(db_index=True, help_text='Brief title of the event', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the event')),
                ('details', models.JSONField(blank=True, help_text='Additional technical details as JSON', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the event occurred')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/user agent information')),
                ('barcode', models.ForeignKey(blank=True, help_text='Related barcode if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='inventory.barcode')),
                ('batch', models.ForeignKey(blank=True, help_text='Related batch if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='inventory.batch')),
                ('service_case', models.ForeignKey(blank=True, help_text='Related service case if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='inventory.servicecase')),
                ('test', models.ForeignKey(blank=True, help_text='Related test if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='inventory.test')),
                ('user', models.ForeignKey(blank=True, help_text='User who triggered the event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Log',
                'verbose_name_plural': 'System Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'level'], name='inventory_s_event_t_b513a4_idx'), models.Index(fields=['-timestamp'], name='inventory_s_timesta_f56988_idx'), models.Index(fields=['user', '-timestamp'], name='inventory_s_user_id_974bf0_idx'), models.Index(fields=['barcode', '-timestamp'], name='inventory_s_barcode_9234ed_idx'), models.Index(fields=['test', '-timestamp'], name='inventory_s_test_id_a2f019_idx'), models.Index(fields=['service_case', '-timestamp'], name='inventory_s_service_634361_idx')],
            },
        ),
    ]
