# Generated by Django 5.2 on 2026-01-08 20:30

from django.db import migrations, models


def migrate_technician_data(apps, schema_editor):
    """Migrate technician ForeignKey to username CharField"""
    ServiceCase = apps.get_model('inventory', 'ServiceCase')
    Technician = apps.get_model('inventory', 'Technician')

    # Use raw SQL to update the data to the new technician_name field
    if schema_editor.connection.vendor == 'sqlite':
        # For SQLite
        schema_editor.execute("""
            UPDATE inventory_servicecase
            SET technician_name = (
                SELECT name FROM inventory_technician
                WHERE inventory_technician.id = inventory_servicecase.technician_id
            )
            WHERE technician_id IS NOT NULL;
        """)
    elif schema_editor.connection.vendor == 'postgresql':
        # For PostgreSQL
        schema_editor.execute("""
            UPDATE inventory_servicecase sc
            SET technician_name = t.name
            FROM inventory_technician t
            WHERE sc.technician_id = t.id;
        """)
    elif schema_editor.connection.vendor == 'mysql':
        # For MySQL
        schema_editor.execute("""
            UPDATE inventory_servicecase sc
            INNER JOIN inventory_technician t ON sc.technician_id = t.id
            SET sc.technician_name = t.name;
        """)

    # Handle any NULL values
    ServiceCase.objects.filter(technician_name__isnull=True).update(technician_name='Unknown')


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_systemlog'),
    ]

    operations = [
        # First, add a temporary field to store the technician name
        migrations.AddField(
            model_name='servicecase',
            name='technician_name',
            field=models.CharField(max_length=150, null=True, blank=True),
        ),
        # Migrate the data
        migrations.RunPython(migrate_technician_data, migrations.RunPython.noop),
        # Remove the old technician field (ForeignKey)
        migrations.RemoveField(
            model_name='servicecase',
            name='technician',
        ),
        # Rename technician_name to technician
        migrations.RenameField(
            model_name='servicecase',
            old_name='technician_name',
            new_name='technician',
        ),
        # Make the field non-nullable with a default
        migrations.AlterField(
            model_name='servicecase',
            name='technician',
            field=models.CharField(default='Unknown', help_text='Username of the service technician assigned to this case', max_length=150),
        ),
        # Rename the index
        migrations.RenameIndex(
            model_name='servicecase',
            new_name='inventory_s_technic_aaddfc_idx',
            old_name='inventory_s_technic_50605b_idx',
        ),
    ]
