# Generated by Django 5.2 on 2026-01-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_rename_inventory_s_technic_50605b_idx_inventory_s_technic_aaddfc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='attachment',
            field=models.URLField(blank=True, help_text='Google Drive link for batch attachments', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='servicecase',
            name='technician',
            field=models.CharField(help_text='Username of the service technician assigned to this case', max_length=150),
        ),
    ]
